=== UO291047/SEW-LaVuelta2026/xml/etapa.dtd
<!ELEMENT etapa (datosEtapa, galeria, ubiSalida, ubiMeta, 
    hitos, puntosAnonimos, clasificacionEtapa, clasificacionGeneral, clasificacionEquipos)>
<!ELEMENT datosEtapa (nombre, numero, longitudEtapa, fecha, 
    datosGanador, desnivel, ubiInicio, ubiFinal, tipoEtapa)>
<!ELEMENT datosGanador (tiempoGanador, velMedia)>
<!ELEMENT galeria (refs, fotos, videos, sonidos)>
<!ELEMENT refs (ref+)>
<!ELEMENT fotos (foto+)>
<!ELEMENT videos (video+)>
<!ELEMENT sonidos (sonido+)>
<!ELEMENT coords (longitud, latitud, altitud)>
<!ELEMENT ubiSalida (coords)>
<!ELEMENT ubiMeta (coords)>
<!ELEMENT hito (tipoHito, coords, distanciaSalida)>
<!ELEMENT hitos (hito+)>
<!ELEMENT puntoAnonimo (nombre, coords, distanciaSalida)>
<!ELEMENT puntosAnonimos (puntoAnonimo+)>
<!ELEMENT clasificacionEtapa (ciclista+, diferencia, diferencia)>
<!ELEMENT clasificacionGeneral (ciclista+, diferencia, diferencia)>
<!ELEMENT clasificacionEquipos (equipo+, diferencia, diferencia)>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT longitudEtapa (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT tiempoGanador (#PCDATA)>
<!ELEMENT velMedia (#PCDATA)>
<!ELEMENT desnivel (#PCDATA)>
<!ELEMENT ubiInicio (#PCDATA)>
<!ELEMENT ubiFinal (#PCDATA)>
<!ELEMENT tipoEtapa (#PCDATA)>
<!ELEMENT ref (#PCDATA)>
<!ELEMENT foto (#PCDATA)>
<!ELEMENT video (#PCDATA)>
<!ELEMENT sonido (#PCDATA)>
<!ELEMENT longitud (#PCDATA)>
<!ELEMENT latitud (#PCDATA)>
<!ELEMENT altitud (#PCDATA)>
<!ELEMENT distanciaSalida (#PCDATA)>
<!ELEMENT tipoHito (#PCDATA)>
<!ELEMENT ciclista (#PCDATA)>
<!ELEMENT equipo (#PCDATA)>
<!ELEMENT diferencia (#PCDATA)>

<!ATTLIST longitudEtapa
    unidades CDATA #REQUIRED>
<!ATTLIST velMedia
    uEspacio CDATA #REQUIRED
    uTiempo CDATA #REQUIRED>
<!ATTLIST desnivel
    unidades CDATA #REQUIRED>
<!ATTLIST longitud
    unidades CDATA #REQUIRED>
<!ATTLIST latitud
    unidades CDATA #REQUIRED>
<!ATTLIST altitud
    unidades CDATA #REQUIRED>
<!ATTLIST distanciaSalida
    unidades CDATA #REQUIRED>
<!ATTLIST tipoHito
    tipo CDATA #REQUIRED>
<!ATTLIST diferencia
    unidades CDATA #REQUIRED>

=== UO291047/SEW-LaVuelta2026/xml/etapa.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE etapa SYSTEM "etapa.dtd">

<etapa>
    <datosEtapa>
        <nombre>La Vila Joiosa-Villajoyosa a Alto de Aitana-Costa Blanca</nombre>
        <numero>9</numero>
        <longitudEtapa unidades="km">187.4</longitudEtapa>
        <fecha>2026-08-30</fecha>
        <datosGanador>
            <tiempoGanador>PT5H10M40S</tiempoGanador>
            <velMedia uEspacio="km" uTiempo="h">36.19</velMedia>
        </datosGanador>
        <desnivel unidades="m">5166</desnivel>
        <ubiInicio>La Vila Joiosa-Villajoyosa</ubiInicio>
        <ubiFinal>Alto de Aitana-Costa Blanca</ubiFinal>
        <tipoEtapa>Montaña</tipoEtapa>
    </datosEtapa>
    <galeria>
        <refs>
            <ref>Libro de ruta - La vuelta 2026</ref>
            <ref>www.lavuelta.es</ref>
            <ref>https://merkabici.es/recorrido-oficial-de-la-vuelta-a-espana-2026/</ref>
        </refs>
        <fotos>
            <foto>foto1.jpg</foto>
            <foto>foto2.jpg</foto>
            <foto>foto3.jpg</foto>
        </fotos>
        <videos>
            <video>video1.mp4</video>
        </videos>
        <sonidos>
            <sonido>sonido1.mp3</sonido>
        </sonidos>
    </galeria>
    <ubiSalida>
        <coords>
            <longitud unidades="decimales de grados">-0.213006</longitud>
            <latitud unidades="decimales de grados">38.538118</latitud>
            <altitud unidades="m">98</altitud>
        </coords>
    </ubiSalida>
    <ubiMeta>
        <coords>
            <longitud unidades="decimales de grados">-0.267632</longitud>
            <latitud unidades="decimales de grados">38.649601</latitud>
            <altitud unidades="m">1543</altitud>
        </coords>
    </ubiMeta>
    <hitos>
        <hito>
            <nombre>Puerto de Tárbena</nombre>
            <tipoHito tipo="2ª categoría">Puerto</tipoHito>
            <coords>
                <longitud unidades="decimales de grados">-0.103679</longitud>
                <latitud unidades="decimales de grados">38.695720</latitud>
                <altitud unidades="m">594</altitud>
            </coords>
            <distanciaSalida unidades="km">36.7</distanciaSalida>
        </hito>
        <hito>
            <nombre>Puerto de El Miserat</nombre>
            <tipoHito tipo="1ª categoría">Puerto</tipoHito>
            <coords>
                <longitud unidades="decimales de grados">-0.175283</longitud>
                <latitud unidades="decimales de grados">38.827861</latitud>
                <altitud unidades="m">634</altitud>
            </coords>
            <distanciaSalida unidades="km">73.9</distanciaSalida>
        </hito>
        <hito>
            <nombre>Puerto de Tollos</nombre>
            <tipoHito tipo="3ª categoría">Puerto</tipoHito>
            <coords>
                <longitud unidades="decimales de grados">-0.267911</longitud>
                <latitud unidades="decimales de grados">38.763113</latitud>
                <altitud unidades="m">829</altitud>
            </coords>
            <distanciaSalida unidades="km">90.7</distanciaSalida>
        </hito>
        <hito>
            <nombre>Puerto de Tudons</nombre>
            <tipoHito tipo="2ª categoría">Puerto</tipoHito>
            <coords>
                <longitud unidades="decimales de grados">-0.324812</longitud>
                <latitud unidades="decimales de grados">38.650303</latitud>
                <altitud unidades="m">1027</altitud>
            </coords>
            <distanciaSalida unidades="km">121.8</distanciaSalida>
        </hito>
        <hito>
            <nombre>Benifallim</nombre>
            <tipoHito tipo="intermedio">Sprint</tipoHito>
            <coords>
                <longitud unidades="decimales de grados">-0.400657</longitud>
                <latitud unidades="decimales de grados">38.662617</latitud>
                <altitud unidades="m">723</altitud>
            </coords>
            <distanciaSalida unidades="km">134.6</distanciaSalida>
        </hito>
        <hito>
            <nombre>Puerto de Benifallim</nombre>
            <tipoHito tipo="2ª categoría">Puerto</tipoHito>
            <coords>
                <longitud unidades="decimales de grados">-0.403961</longitud>
                <latitud unidades="decimales de grados">38.641518</latitud>
                <altitud unidades="m">1013</altitud>
            </coords>
            <distanciaSalida unidades="km">139.9</distanciaSalida>
        </hito>
        <hito>
            <nombre>Alto de Aitana</nombre>
            <tipoHito tipo="1ª categoría">Puerto</tipoHito>
            <coords>
                <longitud unidades="decimales de grados">-0.267632</longitud>
                <latitud unidades="decimales de grados">38.649601</latitud>
                <altitud unidades="m">1543</altitud>
            </coords>
            <distanciaSalida unidades="km">187.4</distanciaSalida>
        </hito>
    </hitos>
    <puntosAnonimos>
        <puntoAnonimo>
            <nombre>Finestrat</nombre>
            <coords>
                <longitud unidades="decimales de grados">-0.210617</longitud>
                <latitud unidades="decimales de grados">38.569156</latitud>
                <altitud unidades="m">259</altitud>
            </coords>
            <distanciaSalida unidades="km">3.1</distanciaSalida>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombre>La Nucia</nombre>
            <coords>
                <longitud unidades="decimales de grados">-0.126468</longitud>
                <latitud unidades="decimales de grados">38.612964</latitud>
                <altitud unidades="m">237</altitud>
            </coords>
            <distanciaSalida unidades="km">18.1</distanciaSalida>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombre>Polop</nombre>
            <coords>
                <longitud unidades="decimales de grados">-0.131854</longitud>
                <latitud unidades="decimales de grados">38.625010</latitud>
                <altitud unidades="m">204</altitud>
            </coords>
            <distanciaSalida unidades="km">20.5</distanciaSalida>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombre>Callosa d'en Sarrià</nombre>
            <coords>
                <longitud unidades="decimales de grados">-0.120736</longitud>
                <latitud unidades="decimales de grados">38.650363</latitud>
                <altitud unidades="m">229</altitud>
            </coords>
            <distanciaSalida unidades="km">24.3</distanciaSalida>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombre>Bolulla</nombre>
            <coords>
                <longitud unidades="decimales de grados">-0.110968</longitud>
                <latitud unidades="decimales de grados">38.676353</latitud>
                <altitud unidades="m">205</altitud>
            </coords>
            <distanciaSalida unidades="km">29.5</distanciaSalida>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombre>Coll de Rates</nombre>
            <coords>
                <longitud unidades="decimales de grados">-0.059602</longitud>
                <latitud unidades="decimales de grados">38.723590</latitud>
                <altitud unidades="m">619</altitud>
            </coords>
            <distanciaSalida unidades="km">43.6</distanciaSalida>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombre>Parcent</nombre>
            <coords>
                <longitud unidades="decimales de grados">-0.070300</longitud>
                <latitud unidades="decimales de grados">38.746550</latitud>
                <altitud unidades="m">269</altitud>
            </coords>
            <distanciaSalida unidades="km">50.3</distanciaSalida>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombre>Orba</nombre>
            <coords>
                <longitud unidades="decimales de grados">-0.065584</longitud>
                <latitud unidades="decimales de grados">38.780808</latitud>
                <altitud unidades="m">145</altitud>
            </coords>
            <distanciaSalida unidades="km">55.5</distanciaSalida>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombre>Sagra</nombre>
            <coords>
                <longitud unidades="decimales de grados">-0.067543</longitud>
                <latitud unidades="decimales de grados">38.817566</latitud>
                <altitud unidades="m">144</altitud>
            </coords>
            <distanciaSalida unidades="km">59.9</distanciaSalida>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombre>Pego</nombre>
            <coords>
                <longitud unidades="decimales de grados">-0.121040</longitud>
                <latitud unidades="decimales de grados">38.838427</latitud>
                <altitud unidades="m">88</altitud>
            </coords>
            <distanciaSalida unidades="km">66.7</distanciaSalida>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombre>Alcalá de la Jovada</nombre>
            <coords>
                <longitud unidades="decimales de grados">-0.251748</longitud>
                <latitud unidades="decimales de grados">38.796087</latitud>
                <altitud unidades="m">629</altitud>
            </coords>
            <distanciaSalida unidades="km">83.7</distanciaSalida>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombre>Beniaia</nombre>
            <coords>
                <longitud unidades="decimales de grados">-0.269471</longitud>
                <latitud unidades="decimales de grados">38.777216</latitud>
                <altitud unidades="m">676</altitud>
            </coords>
            <distanciaSalida unidades="km">88.2</distanciaSalida>
        </puntoAnonimo>
